import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";
import { JsonLd } from "@/components/json-ld";

export const metadata: Metadata = {
  metadataBase: new URL("https://technioz.com"),
  title: {
    default: "Technioz - Innovative Software Development & IT Solutions",
    template: "%s | Technioz",
  },
  description:
    "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project and get a custom roadmap. Transform your business with cutting-edge technology.",
  keywords: [
    "Technioz",
    "Technioz software company",
    "Technioz IT solutions",
    "Technioz digital agency",
    "Technioz technology partner",
    "about Technioz company",
    "Technioz portfolio",
    "Technioz case studies",
    "Technioz client reviews",
    "Technioz testimonials",
    "custom software development company",
    "software development company India",
    "web development company",
    "mobile app development services",
    "AI development company",
    "digital transformation services",
    "cloud application development",
    "enterprise software solutions",
    "business automation software",
    "technology consulting company",
    "SaaS product development",
    "UI UX design services",
    "eCommerce website development",
    "Next.js development company",
    "React development company",
    "React Native development company",
    "Vue.js development company",
    "Angular development services",
    "Node.js development services",
    "PHP web development company",
    "Python development services",
    "Django development company",
    "Laravel development services",
    "WordPress development company",
    "Flutter app development",
    "Swift iOS development",
    "Kotlin Android development",
    "JavaScript development experts",
    "TypeScript development services",
    "full stack development agency",
    "MERN stack development",
    "MEAN stack development",
    "JAMstack development services",
    "progressive web app development",
    "cross-platform app development",
    "hybrid mobile app development",
    "mobile-first web development",
    "iOS app development company",
    "Android app development services",
    "native mobile app development",
    "mobile app UI UX design",
    "app store optimization services",
    "mobile app maintenance support",
    "AWS development services",
    "Azure cloud solutions",
    "Google Cloud Platform development",
    "cloud migration services",
    "cloud-native application development",
    "serverless architecture solutions",
    "microservices-based development",
    "Docker containerization services",
    "Kubernetes orchestration",
    "CI CD pipeline implementation",
    "devops consulting services",
    "infrastructure as code services",
    "cloud security solutions",
    "multi-cloud strategy consulting",
    "AI chatbot development",
    "machine learning solutions",
    "natural language processing apps",
    "computer vision development",
    "predictive analytics software",
    "AI-powered software solutions",
    "AI integration in business",
    "intelligent automation services",
    "AI-driven business solutions",
    "generative AI solutions",
    "ChatGPT integration services",
    "AI model training deployment",
    "deep learning applications",
    "IoT app development company",
    "IoT dashboard design",
    "sensor integration software",
    "blockchain app development services",
    "smart contract development",
    "Web3 development services",
    "crypto wallet app development",
    "NFT marketplace development",
    "DeFi platform development",
    "API development company",
    "RESTful API development",
    "GraphQL API development",
    "API integration services",
    "third-party API integration",
    "backend development services",
    "database design optimization",
    "PostgreSQL development",
    "MongoDB development services",
    "MySQL database solutions",
    "Redis caching implementation",
    "real-time application development",
    "WebSocket development",
    "event-driven architecture experts",
    "frontend development company",
    "responsive website design",
    "mobile UI/UX experts",
    "UI redesign and revamp",
    "interactive dashboard design",
    "design system development",
    "user experience consulting",
    "wireframing prototyping services",
    "frontend optimization services",
    "web accessibility compliance",
    "animation and motion design",
    "digital product design agency",
    "healthcare software solutions",
    "telemedicine software development",
    "hospital management system",
    "patient portal development",
    "medical billing software",
    "HIPAA compliant software",
    "pharmacy management system",
    "health tracking app development",
    "doctor appointment booking app",
    "fintech software development",
    "fintech platform development",
    "banking app development",
    "payment gateway integration",
    "digital wallet development",
    "p2p lending software",
    "loan management software development",
    "financial software for institutions",
    "trading platform development",
    "robo advisor development",
    "insurance tech solutions",
    "KYC verification software",
    "ecommerce mobile app builders",
    "Shopify development company India",
    "WooCommerce development services",
    "Magento development services",
    "headless commerce development",
    "multi-vendor marketplace development",
    "B2B ecommerce platform",
    "D2C ecommerce solutions",
    "POS system development company",
    "inventory management software",
    "order management system",
    "eLearning app development",
    "online learning platform development",
    "learning management system development",
    "virtual classroom software",
    "student information system",
    "course marketplace development",
    "educational game development",
    "logistics app development",
    "fleet management software development",
    "warehouse management system",
    "supply chain software development",
    "delivery tracking app",
    "route optimization software",
    "ride booking app development",
    "vehicle tracking system",
    "real estate platform development",
    "property listing web apps",
    "property management software",
    "real estate CRM development",
    "virtual tour app development",
    "restaurant app development",
    "food delivery app development",
    "restaurant ordering system development",
    "table reservation system",
    "hotel booking app development",
    "travel app development",
    "tour booking platform",
    "HRMS software development",
    "AI-powered HR solutions",
    "performance tracking software",
    "workforce management tools",
    "employee onboarding software",
    "payroll management system",
    "recruitment platform development",
    "attendance tracking system",
    "enterprise mobility solutions",
    "CRM software development",
    "custom CRM development",
    "ERP development services",
    "custom ERP software",
    "business intelligence dashboards",
    "data-driven software development",
    "enterprise digital solutions",
    "B2B software solutions",
    "B2B portal development",
    "B2B SaaS development experts",
    "enterprise resource planning",
    "business process automation",
    "document management system",
    "project management software",
    "collaboration tools development",
    "MVP development for startups",
    "startup tech solutions",
    "technology partner for startups",
    "startup-friendly IT company",
    "SaaS startups solutions",
    "lean startup development",
    "rapid prototyping services",
    "software prototyping services",
    "product market fit consulting",
    "startup CTO consulting",
    "tech partner for accelerators",
    "startup incubation tech partner",
    "idea to product development",
    "startup product development",
    "hire software developers",
    "hire dedicated developers",
    "remote developer team",
    "dedicated software team India",
    "IT staff augmentation India",
    "software team extension services",
    "hire React developers",
    "hire Node.js developers",
    "hire full stack developers",
    "hire mobile app developers",
    "hire UI UX designers",
    "hire DevOps engineers",
    "offshore development team",
    "nearshore development services",
    "on-demand developer hiring",
    "contract software developers",
    "agile software development company",
    "scrum software team",
    "agile transformation consulting",
    "lean software development",
    "iterative development process",
    "continuous delivery services",
    "test-driven development",
    "behavior-driven development",
    "QA and testing services",
    "manual and automation testing",
    "software testing company",
    "quality assurance services",
    "test automation services",
    "performance testing services",
    "security testing services",
    "penetration testing services",
    "mobile app testing services",
    "API testing services",
    "load testing services",
    "usability testing services",
    "software maintenance services",
    "app support and maintenance",
    "software modernization services",
    "legacy software migration",
    "legacy system modernization",
    "app migration services",
    "software project rescue services",
    "technology upgrade services",
    "bug fixing services",
    "performance optimization",
    "code refactoring services",
    "secure app development",
    "GDPR compliant app development",
    "HIPAA compliant development",
    "SOC 2 compliance consulting",
    "ISO certified software company",
    "PCI DSS compliant development",
    "data privacy consulting",
    "cybersecurity consulting",
    "secure code review",
    "vulnerability assessment",
    "custom booking platform development",
    "appointment scheduling software",
    "video conferencing app development",
    "streaming platform development",
    "OTT app development services",
    "social media app development",
    "dating app development",
    "fitness app development",
    "messaging app development",
    "secure messaging platform",
    "encrypted chat app development",
    "live chat software development",
    "community platform development",
    "forum software development",
    "auction platform development",
    "classified app development",
    "job board app development",
    "freelancer platform development",
    "on-demand service app",
    "gig economy platform",
    "marketing automation tools",
    "digital advertising solutions",
    "email marketing platform",
    "SMS marketing software",
    "social media management tools",
    "influencer marketing platform",
    "affiliate marketing software",
    "referral program software",
    "loyalty program development",
    "custom CMS development",
    "headless CMS development",
    "WordPress custom development",
    "content management solutions",
    "blog platform development",
    "publishing platform development",
    "knowledge base software",
    "documentation platform",
    "modular software design",
    "scalable software solutions",
    "high-performance web apps",
    "enterprise-grade mobile apps",
    "multi-tenant SaaS development",
    "white label app development",
    "white label SaaS platforms",
    "API-first development",
    "headless architecture",
    "progressive enhancement",
    "how to build a mobile app for my business",
    "best company for custom software development",
    "cost of developing a mobile app in India",
    "how much does custom software cost",
    "software development company near me",
    "reliable software development partner",
    "experienced app developers for hire",
    "build SaaS product from scratch",
    "migrate legacy system to cloud",
    "modernize outdated software application",
    "offshore vs nearshore development",
    "native vs hybrid app development",
    "React vs Angular for enterprise",
    "AWS vs Azure vs Google Cloud",
    "in-house vs outsourced development",
    "enterprise software development best practices",
    "startup MVP development timeline",
    "mobile app development process steps",
    "web application security checklist",
    "cloud migration strategy guide",
    "API integration best practices",
    "software maintenance cost estimation",
    "software development company in India",
    "custom software development India",
    "web development company India",
    "mobile app development company India",
    "top IT companies in India",
    "best software companies in India",
    "offshore software development India",
    "AI development services India",
    "enterprise software solutions India",
    "cloud application development India",
    "best SaaS development company in India",
    "startup software development India",
    "hire developers in India",
    "software consulting company India",
    "ecommerce website development India",
    "B2B software development India",
    "affordable software development India",
    "web application development India",
    "business automation software India",
    "UI/UX design agency India",
    "React development company India",
    "Node.js developers India",
    "full stack developers India",
    "DevOps company India",
    "Technioz UAE",
    "Technioz Dubai",
    "software development company Dubai",
    "app development company UAE",
    "IT solutions Dubai",
    "digital transformation UAE",
    "web development company Dubai",
    "mobile app developers Dubai",
    "enterprise software UAE",
    "cloud services Dubai",
    "AI development Dubai UAE",
    "Technioz Saudi Arabia",
    "Technioz KSA",
    "software company Saudi Arabia",
    "app development Riyadh",
    "digital solutions KSA",
    "web development Jeddah",
    "enterprise software Saudi Arabia",
    "Technioz Kuwait",
    "software development company Kuwait",
    "app developers Kuwait",
    "IT solutions Kuwait",
    "web development Kuwait City",
    "digital transformation Kuwait",
    "Technioz Qatar",
    "software company Qatar",
    "app development Doha",
    "web development Qatar",
    "enterprise solutions Qatar",
    "Technioz Oman",
    "software development Oman",
    "app development Muscat",
    "IT company Oman",
    "web solutions Oman",
    "digital services Oman",
    "Technioz Bahrain",
    "software company Bahrain",
    "app development Manama",
    "IT solutions Bahrain",
    "web development Bahrain",
    "tech services Bahrain",
    "software development company Middle East",
    "IT services GCC countries",
    "app development Gulf region",
    "enterprise software Middle East",
    "digital transformation GCC",
    "alkhanjry groups technology partner",
    "alkhanjry group technology partner",
    "alkhanjry tech solutions",
    "enterprise technology partnerships",
    "corporate software solutions",
    "digital transformation partner",
    "affordable IT solutions",
    "cost-effective software development",
    "enterprise-grade solutions",
    "scalable technology solutions",
    "future-ready IT infrastructure",
    "software innovation partner",
    "digital innovation company",
    "cutting-edge technology solutions",
    "bespoke software development",
    "tailor-made software solutions",
    "on-time software delivery",
    "transparent software development",
    "agile software delivery",
    "quality software development",
    "experienced software team",
    "trusted technology partner",
    "free consultation software development",
    "free IT consultation",
    "free software development consultation",
    "free 30 minute consultation",
    "free project consultation",
    "free technology consultation",
    "free consultation call",
    "free software consultation",
    "free app development consultation",
    "free web development consultation",
    "free consultation no obligation",
    "free consultation software company",
    "free consultation IT services",
    "schedule free consultation",
    "book free consultation",
    "free consultation software development India",
    "free consultation software development UAE",
    "free consultation software development Dubai",
    "free consultation software experts",
    "free consultation technology experts",
    "free consultation software developers",
    "free consultation digital transformation",
    "free consultation software project",
    "free consultation startup",
    "free consultation enterprise software",
    "free consultation custom software",
    "free consultation mobile app development",
    "free consultation web application development",
    "free consultation software architecture",
    "free consultation technology strategy",
    "free consultation digital strategy",
    "free consultation project roadmap",
    "free consultation cost estimation",
    "free consultation timeline estimation",
    "free consultation software quote",
    "free consultation no credit card",
    "free consultation no commitment",
    "free consultation software development company",
    "free consultation IT consulting",
    "free consultation technology consulting",
    "free consultation software consulting",
    "free consultation business consulting",
    "free consultation technical consulting",
    "free consultation software assessment",
    "free consultation technology assessment",
    "free consultation code review",
    "free consultation technical audit",
    "free consultation project assessment",
    "free consultation requirements analysis",
    "free consultation feasibility study",
    "free consultation proof of concept",
    "free consultation MVP development",
    "free consultation software planning",
    "free consultation technology planning",
    "free consultation software design",
    "free consultation system design",
    "free consultation architecture design",
    "free consultation UI UX design",
    "free consultation software migration",
    "free consultation cloud migration",
    "free consultation software modernization",
    "free consultation legacy system",
    "free consultation system integration",
    "free consultation API integration",
    "free consultation software security",
    "free consultation cybersecurity",
    "free consultation software testing",
    "free consultation QA testing",
    "free consultation DevOps",
    "free consultation cloud services",
    "free consultation AWS",
    "free consultation Azure",
    "free consultation Google Cloud",
    "free consultation performance optimization",
    "free consultation SEO optimization",
    "free consultation software analytics",
    "free consultation business analytics",
    "Stripe payment integration",
    "PayPal integration services",
    "Twilio integration",
    "SendGrid email integration",
    "Google Maps API integration",
    "Firebase integration services",
    "Salesforce integration",
    "HubSpot integration",
    "Zapier integration development",
    "Slack bot development",
    "WhatsApp Business API integration",
    "social media API integration",
    "CRM integration services",
    "ERP integration consulting",
    "website speed optimization",
    "mobile app performance tuning",
    "database optimization services",
    "SEO-friendly web development",
    "Core Web Vitals optimization",
    "PWA performance optimization",
    "CDN integration services",
    "caching strategy implementation",
    "code splitting optimization",
    "digital workplace solutions",
    "remote collaboration platform",
    "enterprise chat app development",
    "workflow automation software",
    "process mining software",
    "RPA development services",
    "low-code development services",
    "no-code platform development",
    "citizen developer enablement",
    "software for small businesses",
    "software for medium enterprises",
    "digital transformation for SMEs",
    "software for digital agencies",
    "global IT services provider",
    "India-based IT service provider",
    "managed IT services provider",
    "IT consulting and advisory",
    "technology roadmap consulting",
    "digital strategy consulting",
    "software architecture consulting",
    "technical debt assessment",
    "code audit services",
    "UI audit services",
    "technical due diligence",
    "software vendor selection",
    "technology stack selection",
    "build vs buy consulting",
    "software company in Jalandhar",
    "IT company in Jalandhar Punjab",
    "web development company in Jalandhar",
    "app development services Jalandhar",
    "mobile app developers in Jalandhar",
    "best software developers Jalandhar",
    "custom software company Jalandhar",
    "website design company Jalandhar",
    "software solutions in Jalandhar",
    "top IT firms in Punjab",
    "Jalandhar based software company",
    "digital transformation company Jalandhar",
    "business automation Jalandhar",
    "enterprise application development Jalandhar",
    "AI software company in Jalandhar",
    "top web designers in Jalandhar",
    "cloud software development Jalandhar",
    "PHP development in Jalandhar",
    "Node.js developers in Jalandhar",
    "best UI/UX agency in Jalandhar",
    "hire developers in Jalandhar",
    "IT services Punjab",
    "software companies in Punjab",
    "software company in Dubai",
    "software company in Oman",
    "software company in Abu Dhabi",
    "software company in Saudi Arabia",
    "software company in KSA",
    "software company in Qatar",
    "software company in UAE",
    "software company in Muscat",
    "IT company in Dubai",
    "IT company in Oman",
    "IT company in Abu Dhabi",
    "IT company in Saudi Arabia",
    "IT company in KSA",
    "IT company in Qatar",
    "IT company in UAE",
    "IT company in Muscat",
    "web development company in Dubai",
    "web development company in Oman",
    "web development company in Abu Dhabi",
    "web development company in Saudi Arabia",
    "web development company in KSA",
    "web development company in Qatar",
    "web development company in UAE",
    "web development company in Muscat",
    "app development services Dubai",
    "app development services Oman",
    "app development services Abu Dhabi",
    "app development services Saudi Arabia",
    "app development services KSA",
    "app development services Qatar",
    "app development services UAE",
    "app development services Muscat",
    "mobile app developers in Dubai",
    "mobile app developers in Oman",
    "mobile app developers in Abu Dhabi",
    "mobile app developers in Saudi Arabia",
    "mobile app developers in KSA",
    "mobile app developers in Qatar",
    "mobile app developers in UAE",
    "mobile app developers in Muscat",
    "best software developers Dubai",
    "best software developers Oman",
    "best software developers Abu Dhabi",
    "best software developers Saudi Arabia",
    "best software developers KSA",
    "best software developers Qatar",
    "best software developers UAE",
    "best software developers Muscat",
    "custom software company Dubai",
    "custom software company Oman",
    "custom software company Abu Dhabi",
    "custom software company Saudi Arabia",
    "custom software company KSA",
    "custom software company Qatar",
    "custom software company UAE",
    "custom software company Muscat",
    "website design company Dubai",
    "website design company Oman",
    "website design company Abu Dhabi",
    "website design company Saudi Arabia",
    "website design company KSA",
    "website design company Qatar",
    "website design company UAE",
    "website design company Muscat",
    "software solutions in Dubai",
    "software solutions in Oman",
    "software solutions in Abu Dhabi",
    "software solutions in Saudi Arabia",
    "software solutions in KSA",
    "software solutions in Qatar",
    "software solutions in UAE",
    "software solutions in Muscat",
    "top IT firms in Dubai",
    "top IT firms in Oman",
    "top IT firms in Abu Dhabi",
    "top IT firms in Saudi Arabia",
    "top IT firms in KSA",
    "top IT firms in Qatar",
    "top IT firms in UAE",
    "top IT firms in Muscat",
    "Dubai based software company",
    "Oman based software company",
    "Abu Dhabi based software company",
    "Saudi Arabia based software company",
    "KSA based software company",
    "Qatar based software company",
    "UAE based software company",
    "Muscat based software company",
    "digital transformation company Dubai",
    "digital transformation company Oman",
    "digital transformation company Abu Dhabi",
    "digital transformation company Saudi Arabia",
    "digital transformation company KSA",
    "digital transformation company Qatar",
    "digital transformation company UAE",
    "digital transformation company Muscat",
    "business automation Dubai",
    "business automation Oman",
    "business automation Abu Dhabi",
    "business automation Saudi Arabia",
    "business automation KSA",
    "business automation Qatar",
    "business automation UAE",
    "business automation Muscat",
    "enterprise application development Dubai",
    "enterprise application development Oman",
    "enterprise application development Abu Dhabi",
    "enterprise application development Saudi Arabia",
    "enterprise application development KSA",
    "enterprise application development Qatar",
    "enterprise application development UAE",
    "enterprise application development Muscat",
    "AI software company in Dubai",
    "AI software company in Oman",
    "AI software company in Abu Dhabi",
    "AI software company in Saudi Arabia",
    "AI software company in KSA",
    "AI software company in Qatar",
    "AI software company in UAE",
    "AI software company in Muscat",
    "top web designers in Dubai",
    "top web designers in Oman",
    "top web designers in Abu Dhabi",
    "top web designers in Saudi Arabia",
    "top web designers in KSA",
    "top web designers in Qatar",
    "top web designers in UAE",
    "top web designers in Muscat",
    "cloud software development Dubai",
    "cloud software development Oman",
    "cloud software development Abu Dhabi",
    "cloud software development Saudi Arabia",
    "cloud software development KSA",
    "cloud software development Qatar",
    "cloud software development UAE",
    "cloud software development Muscat",
    "PHP development in Dubai",
    "PHP development in Oman",
    "PHP development in Abu Dhabi",
    "PHP development in Saudi Arabia",
    "PHP development in KSA",
    "PHP development in Qatar",
    "PHP development in UAE",
    "PHP development in Muscat",
    "Node.js developers in Dubai",
    "Node.js developers in Oman",
    "Node.js developers in Abu Dhabi",
    "Node.js developers in Saudi Arabia",
    "Node.js developers in KSA",
    "Node.js developers in Qatar",
    "Node.js developers in UAE",
    "Node.js developers in Muscat",
    "best UI/UX agency in Dubai",
    "best UI/UX agency in Oman",
    "best UI/UX agency in Abu Dhabi",
    "best UI/UX agency in Saudi Arabia",
    "best UI/UX agency in KSA",
    "best UI/UX agency in Qatar",
    "best UI/UX agency in UAE",
    "best UI/UX agency in Muscat",
    "hire developers in Dubai",
    "hire developers in Oman",
    "hire developers in Abu Dhabi",
    "hire developers in Saudi Arabia",
    "hire developers in KSA",
    "hire developers in Qatar",
    "hire developers in UAE",
    "hire developers in Muscat",
    "IT services Dubai",
    "IT services Oman",
    "IT services Abu Dhabi",
    "IT services Saudi Arabia",
    "IT services KSA",
    "IT services Qatar",
    "IT services UAE",
    "IT services Muscat",
    "software companies in Dubai",
    "software companies in Oman",
    "software companies in Abu Dhabi",
    "software companies in Saudi Arabia",
    "software companies in KSA",
    "software companies in Qatar",
    "software companies in UAE",
    "software companies in Muscat"
  ],
  authors: [{ name: "Technioz Team", url: "https://technioz.com" }],
  creator: "Technioz",
  publisher: "Technioz",
  robots: {
    index: true,
    follow: true,
    googleBot: "index, follow, max-video-preview:-1, max-image-preview:large, max-snippet:-1",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://technioz.com",
    siteName: "Technioz",
    title: "Technioz - Innovative Software Development & IT Solutions",
    description:
      "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project and get a custom roadmap.",
    images: [
      {
        url: "/logo.webp",
        width: 1200,
        height: 630,
        alt: "Technioz - Software Development Company",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Technioz - Innovative Software Development & IT Solutions",
    description:
      "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project.",
    images: ["/logo.webp"],
  },
  alternates: {
    canonical: "https://technioz.com",
  },
  verification: {
    other: {
      "msvalidate.01": "815380119EFE87A1BC1C3A90FA4B6EB6",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <head>
        <JsonLd />
      </head>
      <body>
        <Nav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
