import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";
import { JsonLd } from "@/components/json-ld";

export const metadata: Metadata = {
  metadataBase: new URL("https://technioz.com"),
  title: {
    default: "Technioz - Innovative Software Development & IT Solutions",
    template: "%s | Technioz",
  },
  description:
    "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project and get a custom roadmap. Transform your business with cutting-edge technology.",
  keywords: [
    "Technioz",
    "Technioz software company",
    "Technioz IT solutions",
    "Technioz digital agency",
    "Technioz technology partner",
    "about Technioz company",
    "Technioz portfolio",
    "Technioz case studies",
    "Technioz client reviews",
    "Technioz testimonials",
    "custom software development company",
    "software development company India",
    "web development company",
    "mobile app development services",
    "AI development company",
    "digital transformation services",
    "cloud application development",
    "enterprise software solutions",
    "business automation software",
    "technology consulting company",
    "SaaS product development",
    "UI UX design services",
    "eCommerce website development",
    "Next.js development company",
    "React development company",
    "React Native development company",
    "Vue.js development company",
    "Angular development services",
    "Node.js development services",
    "PHP web development company",
    "Python development services",
    "Django development company",
    "Laravel development services",
    "WordPress development company",
    "Flutter app development",
    "Swift iOS development",
    "Kotlin Android development",
    "JavaScript development experts",
    "TypeScript development services",
    "full stack development agency",
    "MERN stack development",
    "MEAN stack development",
    "JAMstack development services",
    "progressive web app development",
    "cross-platform app development",
    "hybrid mobile app development",
    "mobile-first web development",
    "iOS app development company",
    "Android app development services",
    "native mobile app development",
    "mobile app UI UX design",
    "app store optimization services",
    "mobile app maintenance support",
    "AWS development services",
    "Azure cloud solutions",
    "Cloud Platform development",
    "cloud migration services",
    "cloud-native application development",
    "serverless hitecture solutions",
    "microservices-based development",
    "Docker containerization services",
    "Kubernetes orchestration",
    "CI CD pipeline implementation",
    "devops consulting services",
    "infrastructure as code services",
    "cloud security solutions",
    "multi-cloud strategy consulting",
    "AI chatbot development",
    "machine learning solutions",
    "natural language processing apps",
    "computer vision development",
    "predictive analytics software",
    "AI-powered software solutions",
    "AI integration in business",
    "intelligent automation services",
    "AI-driven business solutions",
    "generative AI solutions",
    "ChatGPT integration services",
    "AI model training deployment",
    "deep learning applications",
    "IoT app development company",
    "IoT dashboard design",
    "sensor integration software",
    "blockchain app development services",
    "smart contract development",
    "Web3 development services",
    "crypto wallet app development",
    "NFT marketplace development",
    "DeFi platform development",
    "API development company",
    "RESTful API development",
    "GraphQL API development",
    "API integration services",
    "third-party API integration",
    "backend development services",
    "database design optimization",
    "PostgreSQL development",
    "MongoDB development services",
    "MySQL database solutions",
    "Redis caching implementation",
    "real-time application development",
    "WebSocket development",
    "event-driven hitecture experts",
    "frontend development company",
    "responsive website design",
    "mobile UI/UX experts",
    "UI redesign and revamp",
    "interactive dashboard design",
    "design system development",
    "user experience consulting",
    "wireframing prototyping services",
    "frontend optimization services",
    "web accessibility compliance",
    "animation and motion design",
    "digital product design agency",
    "healthcare software solutions",
    "telemedicine software development",
    "hospital management system",
    "patient portal development",
    "medical billing software",
    "HIPAA compliant software",
    "pharmacy management system",
    "health tracking app development",
    "doctor appointment booking app",
    "fintech software development",
    "fintech platform development",
    "banking app development",
    "payment gateway integration",
    "digital wallet development",
    "p2p lending software",
    "loan management software development",
    "financial software for institutions",
    "trading platform development",
    "robo advisor development",
    "insurance tech solutions",
    "KYC verification software",
    "ecommerce mobile app builders",
    "Shopify development company India",
    "WooCommerce development services",
    "Magento development services",
    "headless commerce development",
    "multi-vendor marketplace development",
    "B2B ecommerce platform",
    "D2C ecommerce solutions",
    "POS system development company",
    "inventory management software",
    "order management system",
    "eLearning app development",
    "online learning platform development",
    "learning management system development",
    "virtual classroom software",
    "student information system",
    "course marketplace development",
    "educational game development",
    "logistics app development",
    "fleet management software development",
    "warehouse management system",
    "supply chain software development",
    "delivery tracking app",
    "route optimization software",
    "ride booking app development",
    "vehicle tracking system",
    "real estate platform development",
    "property listing web apps",
    "property management software",
    "real estate CRM development",
    "virtual tour app development",
    "restaurant app development",
    "food delivery app development",
    "restaurant ordering system development",
    "table reservation system",
    "hotel booking app development",
    "travel app development",
    "tour booking platform",
    "HRMS software development",
    "AI-powered HR solutions",
    "performance tracking software",
    "workforce management tools",
    "employee onboarding software",
    "payroll management system",
    "recruitment platform development",
    "attendance tracking system",
    "enterprise mobility solutions",
    "CRM software development",
    "custom CRM development",
    "ERP development services",
    "custom ERP software",
    "business intelligence dashboards",
    "data-driven software development",
    "enterprise digital solutions",
    "B2B software solutions",
    "B2B portal development",
    "B2B SaaS development experts",
    "enterprise resource planning",
    "business process automation",
    "document management system",
    "project management software",
    "collaboration tools development",
    "MVP development for startups",
    "startup tech solutions",
    "technology partner for startups",
    "startup-friendly IT company",
    "SaaS startups solutions",
    "lean startup development",
    "rapid prototyping services",
    "software prototyping services",
    "product market fit consulting",
    "startup CTO consulting",
    "tech partner for accelerators",
    "startup incubation tech partner",
    "idea to product development",
    "startup product development",
    "hire software developers",
    "hire dedicated developers",
    "remote developer team",
    "dedicated software team India",
    "IT staff augmentation India",
    "software team extension services",
    "hire React developers",
    "hire Node.js developers",
    "hire full stack developers",
    "hire mobile app developers",
    "hire UI UX designers",
    "hire DevOps engineers",
    "offshore development team",
    "nearshore development services",
    "on-demand developer hiring",
    "contract software developers",
    "agile software development company",
    "scrum software team",
    "agile transformation consulting",
    "lean software development",
    "iterative development process",
    "continuous delivery services",
    "test-driven development",
    "behavior-driven development",
    "QA and testing services",
    "manual and automation testing",
    "software testing company",
    "quality assurance services",
    "test automation services",
    "performance testing services",
    "security testing services",
    "penetration testing services",
    "mobile app testing services",
    "API testing services",
    "load testing services",
    "usability testing services",
    "software maintenance services",
    "app support and maintenance",
    "software modernization services",
    "legacy software migration",
    "legacy system modernization",
    "app migration services",
    "software project rescue services",
    "technology upgrade services",
    "bug fixing services",
    "performance optimization",
    "code refactoring services",
    "secure app development",
    "GDPR compliant app development",
    "HIPAA compliant development",
    "SOC 2 compliance consulting",
    "ISO certified software company",
    "PCI DSS compliant development",
    "data privacy consulting",
    "cybersecurity consulting",
    "secure code review",
    "vulnerability assessment",
    "custom booking platform development",
    "appointment scheduling software",
    "video conferencing app development",
    "streaming platform development",
    "OTT app development services",
    "social media app development",
    "dating app development",
    "fitness app development",
    "messaging app development",
    "secure messaging platform",
    "encrypted chat app development",
    "live chat software development",
    "community platform development",
    "forum software development",
    "auction platform development",
    "classified app development",
    "job board app development",
    "platform development",
    "on-demand service app",
    "gig economy platform",
    "marketing automation tools",
    "digital advertising solutions",
    "email marketing platform",
    "SMS marketing software",
    "social media management tools",
    "influencer marketing platform",
    "affiliate marketing software",
    "referral program software",
    "loyalty program development",
    "custom CMS development",
    "headless CMS development",
    "WordPress custom development",
    "content management solutions",
    "blog platform development",
    "publishing platform development",
    "knowledge base software",
    "documentation platform",
    "modular software design",
    "scalable software solutions",
    "high-performance web apps",
    "enterprise-grade mobile apps",
    "multi-tenant SaaS development",
    "white label app development",
    "white label SaaS platforms",
    "API-first development",
    "headless hitecture",
    "progressive enhancement",
    "how to build a mobile app for my business",
    "best company for custom software development",
    "cost of developing a mobile app in India",
    "how much does custom software cost",
    "software development company near me",
    "reliable software development partner",
    "experienced app developers for hire",
    "build SaaS product from scratch",
    "migrate legacy system to cloud",
    "modernize outdated software application",
    "offshore vs nearshore development",
    "native vs hybrid app development",
    "React vs Angular for enterprise",
    "AWS vs Azure vs Cloud",
    "in-house vs outsourced development",
    "enterprise software development best practices",
    "startup MVP development timeline",
    "mobile app development process steps",
    "web application security checklist",
    "cloud migration strategy guide",
    "API integration best practices",
    "software maintenance cost estimation",
    "software development company in India",
    "custom software development India",
    "web development company India",
    "mobile app development company India",
    "top IT companies in India",
    "best software companies in India",
    "offshore software development India",
    "AI development services India",
    "enterprise software solutions India",
    "cloud application development India",
    "best SaaS development company in India",
    "startup software development India",
    "hire developers in India",
    "software consulting company India",
    "ecommerce website development India",
    "B2B software development India",
    "affordable software development India",
    "web application development India",
    "business automation software India",
    "UI/UX design agency India",
    "React development company India",
    "Node.js developers India",
    "full stack developers India",
    "DevOps company India",
    "Technioz UAE",
    "Technioz Dubai",
    "software development company Dubai",
    "app development company UAE",
    "IT solutions Dubai",
    "digital transformation UAE",
    "web development company Dubai",
    "mobile app developers Dubai",
    "enterprise software UAE",
    "cloud services Dubai",
    "AI development Dubai UAE",
    "Technioz Saudi Arabia",
    "Technioz KSA",
    "software company Saudi Arabia",
    "app development Riyadh",
    "digital solutions KSA",
    "web development Jeddah",
    "enterprise software Saudi Arabia",
    "Technioz Kuwait",
    "software development company Kuwait",
    "app developers Kuwait",
    "IT solutions Kuwait",
    "web development Kuwait City",
    "digital transformation Kuwait",
    "Technioz Qatar",
    "software company Qatar",
    "app development Doha",
    "web development Qatar",
    "enterprise solutions Qatar",
    "Technioz Oman",
    "software development Oman",
    "app development Muscat",
    "IT company Oman",
    "web solutions Oman",
    "digital services Oman",
    "Technioz Bahrain",
    "software company Bahrain",
    "app development Manama",
    "IT solutions Bahrain",
    "web development Bahrain",
    "tech services Bahrain",
    "software development company Middle East",
    "IT services GCC countries",
    "app development Gulf region",
    "enterprise software Middle East",
    "digital transformation GCC",
    "alkhanjry groups technology partner",
    "alkhanjry group technology partner",
    "alkhanjry tech solutions",
    "enterprise technology partnerships",
    "corporate software solutions",
    "digital transformation partner",
    "affordable IT solutions",
    "cost-effective software development",
    "enterprise-grade solutions",
    "scalable technology solutions",
    "future-ready IT infrastructure",
    "software innovation partner",
    "digital innovation company",
    "cutting-edge technology solutions",
    "bespoke software development",
    "tailor-made software solutions",
    "on-time software delivery",
    "transparent software development",
    "agile software delivery",
    "quality software development",
    "experienced software team",
    "trusted technology partner",
    "free consultation software development",
    "free IT consultation",
    "free software development consultation",
    "free 30 minute consultation",
    "free project consultation",
    "free technology consultation",
    "free consultation call",
    "free software consultation",
    "free app development consultation",
    "free web development consultation",
    "free consultation no obligation",
    "free consultation software company",
    "free consultation IT services",
    "schedule free consultation",
    "book free consultation",
    "free consultation software development India",
    "free consultation software development UAE",
    "free consultation software development Dubai",
    "free consultation software experts",
    "free consultation technology experts",
    "free consultation software developers",
    "free consultation digital transformation",
    "free consultation software project",
    "free consultation startup",
    "free consultation enterprise software",
    "free consultation custom software",
    "free consultation mobile app development",
    "free consultation web application development",
    "free consultation software hitecture",
    "free consultation technology strategy",
    "free consultation digital strategy",
    "free consultation project roadmap",
    "free consultation cost estimation",
    "free consultation timeline estimation",
    "free consultation software quote",
    "free consultation no credit card",
    "free consultation no commitment",
    "free consultation software development company",
    "free consultation IT consulting",
    "free consultation technology consulting",
    "free consultation software consulting",
    "free consultation business consulting",
    "free consultation technical consulting",
    "free consultation software assessment",
    "free consultation technology assessment",
    "free consultation code review",
    "free consultation technical audit",
    "free consultation project assessment",
    "free consultation requirements analysis",
    "free consultation feasibility study",
    "free consultation proof of concept",
    "free consultation MVP development",
    "free consultation software planning",
    "free consultation technology planning",
    "free consultation software design",
    "free consultation system design",
    "free consultation hitecture design",
    "free consultation UI UX design",
    "free consultation software migration",
    "free consultation cloud migration",
    "free consultation software modernization",
    "free consultation legacy system",
    "free consultation system integration",
    "free consultation API integration",
    "free consultation software security",
    "free consultation cybersecurity",
    "free consultation software testing",
    "free consultation QA testing",
    "free consultation DevOps",
    "free consultation cloud services",
    "free consultation AWS",
    "free consultation Azure",
    "free consultation Cloud",
    "free consultation performance optimization",
    "free consultation SEO optimization",
    "free consultation software analytics",
    "free consultation business analytics",
    "Stripe payment integration",
    "PayPal integration services",
    "Twilio integration",
    "SendGrid email integration",
    "Maps API integration",
    "Firebase integration services",
    "integration",
    "HubSpot integration",
    "Zapier integration development",
    "Slack bot development",
    "Whatp Business API integration",
    "social media API integration",
    "CRM integration services",
    "ERP integration consulting",
    "website speed optimization",
    "mobile app performance tuning",
    "database optimization services",
    "SEO-friendly web development",
    "Core Web Vitals optimization",
    "PWA performance optimization",
    "CDN integration services",
    "caching strategy implementation",
    "code splitting optimization",
    "digital workplace solutions",
    "remote collaboration platform",
    "enterprise chat app development",
    "workflow automation software",
    "process mining software",
    "RPA development services",
    "low-code development services",
    "no-code platform development",
    "citizen developer enablement",
    "software for small businesses",
    "software for medium enterprises",
    "digital transformation for SMEs",
    "software for digital agencies",
    "global IT services provider",
    "India-based IT service provider",
    "managed IT services provider",
    "IT consulting and advisory",
    "technology roadmap consulting",
    "digital strategy consulting",
    "software hitecture consulting",
    "technical debt assessment",
    "code audit services",
    "UI audit services",
    "technical due diligence",
    "software vendor selection",
    "technology stack selection",
    "build vs buy consulting",
    "software company in Jalandhar",
    "IT company in Jalandhar Punjab",
    "web development company in Jalandhar",
    "app development services Jalandhar",
    "mobile app developers in Jalandhar",
    "best software developers Jalandhar",
    "custom software company Jalandhar",
    "website design company Jalandhar",
    "software solutions in Jalandhar",
    "top IT firms in Punjab",
    "Jalandhar based software company",
    "digital transformation company Jalandhar",
    "business automation Jalandhar",
    "enterprise application development Jalandhar",
    "AI software company in Jalandhar",
    "top web designers in Jalandhar",
    "cloud software development Jalandhar",
    "PHP development in Jalandhar",
    "Node.js developers in Jalandhar",
    "best UI/UX agency in Jalandhar",
    "hire developers in Jalandhar",
    "IT services Punjab",
    "software companies in Punjab",
    "software company in Dubai",
    "software company in Oman",
    "software company in Abu Dhabi",
    "software company in Saudi Arabia",
    "software company in KSA",
    "software company in Qatar",
    "software company in UAE",
    "software company in Muscat",
    "IT company in Dubai",
    "IT company in Oman",
    "IT company in Abu Dhabi",
    "IT company in Saudi Arabia",
    "IT company in KSA",
    "IT company in Qatar",
    "IT company in UAE",
    "IT company in Muscat",
    "web development company in Dubai",
    "web development company in Oman",
    "web development company in Abu Dhabi",
    "web development company in Saudi Arabia",
    "web development company in KSA",
    "web development company in Qatar",
    "web development company in UAE",
    "web development company in Muscat",
    "app development services Dubai",
    "app development services Oman",
    "app development services Abu Dhabi",
    "app development services Saudi Arabia",
    "app development services KSA",
    "app development services Qatar",
    "app development services UAE",
    "app development services Muscat",
    "mobile app developers in Dubai",
    "mobile app developers in Oman",
    "mobile app developers in Abu Dhabi",
    "mobile app developers in Saudi Arabia",
    "mobile app developers in KSA",
    "mobile app developers in Qatar",
    "mobile app developers in UAE",
    "mobile app developers in Muscat",
    "best software developers Dubai",
    "best software developers Oman",
    "best software developers Abu Dhabi",
    "best software developers Saudi Arabia",
    "best software developers KSA",
    "best software developers Qatar",
    "best software developers UAE",
    "best software developers Muscat",
    "custom software company Dubai",
    "custom software company Oman",
    "custom software company Abu Dhabi",
    "custom software company Saudi Arabia",
    "custom software company KSA",
    "custom software company Qatar",
    "custom software company UAE",
    "custom software company Muscat",
    "website design company Dubai",
    "website design company Oman",
    "website design company Abu Dhabi",
    "website design company Saudi Arabia",
    "website design company KSA",
    "website design company Qatar",
    "website design company UAE",
    "website design company Muscat",
    "software solutions in Dubai",
    "software solutions in Oman",
    "software solutions in Abu Dhabi",
    "software solutions in Saudi Arabia",
    "software solutions in KSA",
    "software solutions in Qatar",
    "software solutions in UAE",
    "software solutions in Muscat",
    "top IT firms in Dubai",
    "top IT firms in Oman",
    "top IT firms in Abu Dhabi",
    "top IT firms in Saudi Arabia",
    "top IT firms in KSA",
    "top IT firms in Qatar",
    "top IT firms in UAE",
    "top IT firms in Muscat",
    "Dubai based software company",
    "Oman based software company",
    "Abu Dhabi based software company",
    "Saudi Arabia based software company",
    "KSA based software company",
    "Qatar based software company",
    "UAE based software company",
    "Muscat based software company",
    "digital transformation company Dubai",
    "digital transformation company Oman",
    "digital transformation company Abu Dhabi",
    "digital transformation company Saudi Arabia",
    "digital transformation company KSA",
    "digital transformation company Qatar",
    "digital transformation company UAE",
    "digital transformation company Muscat",
    "business automation Dubai",
    "business automation Oman",
    "business automation Abu Dhabi",
    "business automation Saudi Arabia",
    "business automation KSA",
    "business automation Qatar",
    "business automation UAE",
    "business automation Muscat",
    "enterprise application development Dubai",
    "enterprise application development Oman",
    "enterprise application development Abu Dhabi",
    "enterprise application development Saudi Arabia",
    "enterprise application development KSA",
    "enterprise application development Qatar",
    "enterprise application development UAE",
    "enterprise application development Muscat",
    "AI software company in Dubai",
    "AI software company in Oman",
    "AI software company in Abu Dhabi",
    "AI software company in Saudi Arabia",
    "AI software company in KSA",
    "AI software company in Qatar",
    "AI software company in UAE",
    "AI software company in Muscat",
    "top web designers in Dubai",
    "top web designers in Oman",
    "top web designers in Abu Dhabi",
    "top web designers in Saudi Arabia",
    "top web designers in KSA",
    "top web designers in Qatar",
    "top web designers in UAE",
    "top web designers in Muscat",
    "cloud software development Dubai",
    "cloud software development Oman",
    "cloud software development Abu Dhabi",
    "cloud software development Saudi Arabia",
    "cloud software development KSA",
    "cloud software development Qatar",
    "cloud software development UAE",
    "cloud software development Muscat",
    "PHP development in Dubai",
    "PHP development in Oman",
    "PHP development in Abu Dhabi",
    "PHP development in Saudi Arabia",
    "PHP development in KSA",
    "PHP development in Qatar",
    "PHP development in UAE",
    "PHP development in Muscat",
    "Node.js developers in Dubai",
    "Node.js developers in Oman",
    "Node.js developers in Abu Dhabi",
    "Node.js developers in Saudi Arabia",
    "Node.js developers in KSA",
    "Node.js developers in Qatar",
    "Node.js developers in UAE",
    "Node.js developers in Muscat",
    "best UI/UX agency in Dubai",
    "best UI/UX agency in Oman",
    "best UI/UX agency in Abu Dhabi",
    "best UI/UX agency in Saudi Arabia",
    "best UI/UX agency in KSA",
    "best UI/UX agency in Qatar",
    "best UI/UX agency in UAE",
    "best UI/UX agency in Muscat",
    "hire developers in Dubai",
    "hire developers in Oman",
    "hire developers in Abu Dhabi",
    "hire developers in Saudi Arabia",
    "hire developers in KSA",
    "hire developers in Qatar",
    "hire developers in UAE",
    "hire developers in Muscat",
    "IT services Dubai",
    "IT services Oman",
    "IT services Abu Dhabi",
    "IT services Saudi Arabia",
    "IT services KSA",
    "IT services Qatar",
    "IT services UAE",
    "IT services Muscat",
    "software companies in Dubai",
    "software companies in Oman",
    "software companies in Abu Dhabi",
    "software companies in Saudi Arabia",
    "software companies in KSA",
    "software companies in Qatar",
    "software companies in UAE",
    "software companies in Muscat",
    "Custom Mobile App Development Company in Dubai",
    "Best Mobile app development company in Dubai",
    "Provides Reliable Web App Development Services in Dubai",
    "mobile app development team",
    "Embrace The Future of Mobile App Development In Dubai - .",
    "mobile app development company in Dubai",
    "building mobile apps",
    "mobile app development",
    "Develop the app",
    "web app development company in Dubai",
    "fitness app development company",
    "mobile app development company",
    "app development company",
    "How to Hire the Best AI Developer for Your Custom Project",
    "develop chatbots",
    "Top - Tire Mobile App Development Company in Dubai",
    "software development company",
    "mobile apps",
    "web application development company in Dubai",
    "web app development company",
    "web design company in Dubai",
    "Mobile app developers",
    "web app development services in Dubai",
    "cybersecurity",
    "web development",
    "chatbots",
    "software development",
    "mobile app development company in Saudi Arabia",
    "Android app development company in Dubai",
    "Flutter app development company",
    "View product on company website",
    "AI developers",
    "app development",
    "mobile app",
    "Generative AI provides",
    "payment gateways",
    "Web App Development",
    "web app development in Dubai",
    "software app development company",
    "Visit Website",
    "website design company in Dubai",
    "according to industry analysis",
    "Web App Development Services in UAE",
    "mobile app development companies",
    "digital marketing",
    "secure payment gateways",
    "Flutter app development company in Dubai",
    "Generative AI",
    "web application service",
    "web design company",
    "development for Android mobile app development",
    "Web app development company in Dubai.",
    "chatbot",
    "Modern fintech apps",
    "skilled developers",
    "mobile app development company in Abu Dhabi",
    "development costs",
    "Android app development company",
    "mobile app development company UAE",
    "Website",
    "custom software development",
    "cost of software development",
    "build software",
    "software solutions",
    "Create React App",
    "React Native app development company in Dubai",
    "developing a successful mobile application",
    "cost of creating a recipe mobile app",
    "developing software",
    "software development services",
    "Android app development in Dubai",
    "iOS app development company in Dubai",
    "supply chain management",
    "Mobile Application Development Company in Dubai",
    "Android app development companies in the UAE",
    "develop mobile-based CRM software",
    "Telemedicine app",
    "customer relationship stronger",
    "leading website development company",
    "cost of developing a mobile app",
    "robust cybersecurity strategy",
    "ERP software",
    "develop Telecommunication apps using Gen AI",
    "software development companies",
    "how much does app maintenance cost",
    "Developing a mobile app",
    "custom mobile app development companies in Dubai",
    "Software Development Company in Dubai",
    "iOS and Android",
    "mobile application development company",
    "web design company in Dubai.",
    "cybersecurity services",
    "developing a new mobile application",
    "website development company in Dubai",
    "mobile app development process",
    "web applications",
    "outsourced software development company",
    "SaaS companies",
    "develop the app for Android",
    "software development companies in Dubai",
    "mobile development",
    "developers",
    "Flutter app development services in Dubai",
    "mobile app development in 2024",
    "Document management software",
    "ERP tools",
    "develop software systems",
    "website design agency",
    "Android app development company in Saudi Arabia",
    "telemedicine applications",
    "progressive web apps (PWAs)",
    "Web application development",
    "AI chatbots",
    "development of mobile apps",
    "fintech app development company",
    "$898 billion by 2029",
    "pay when they look forward to developing a SaaS-based mobile application",
    "app development solutions",
    "CRM",
    "secure payment gateway integration",
    "cost of developing an eCommerce app in UAE",
    "web development in Dubai",
    "Android application development Company Dubai",
    "develop high-quality iOS apps",
    "software services company",
    "cost of developing",
    "artificial intelligence",
    "app developers in Dubai",
    "mobile developer",
    "How Much Does it Cost to Build a Mobile App in Saudi Arabia?",
    "mobile apps development company",
    "iOS app development",
    "cost of Android app",
    "app ekuvandudza makambani",
    "developers to build applications",
    "web application development company in Dubai.",
    "eCommerce app development in Dubai",
    "web application framework developed",
    "The Ultimate Guide to Estimating Real Estate App Development Cost in UAE",
    "scalable iOS solutions",
    "developers to build apps",
    "iOS Mobile App development Dubai",
    "develop an app like Ask AI",
    "Native app development",
    "telemedicine",
    "Billing software in USA",
    "supply chain processes.",
    "web application development company",
    "Custom ERP Software in Healthcare: A Comprehensive Guide",
    "mobile app developer",
    "UAE",
    "developing high-quality mobile applications",
    "software engineer",
    "DevOps in healthcare",
    "developing a sports app",
    "website design company",
    "custom android app development company",
    "payment gateway",
    "ecommerce Development Company UAE",
    "How to Build Custom Supply Chain Management Software",
    "AI development",
    "Efficient inventory management",
    "Cybersecurity software solutions",
    "How Much Does It Cost To Develop Inventory Management Software",
    "project management platforms",
    "web developer",
    "mobile app development Dubai",
    "custom PHP web application development",
    "Web design and development services",
    "mobile applications",
    "asset tracking management software",
    "develop a mobile app",
    "mobile development team",
    "app development process",
    "develop custom ERP software",
    "web design",
    "Android app development company in UAE",
    "Custom Web App Development Company in Dubai",
    "mobile app development in Saudi Arabia",
    "Web Application Development Company Dubai",
    "Android app development agency in Dubai",
    "web app",
    "develop a simple web app",
    "Mobile Development Services",
    "cost of web app development",
    "developing mobile apps",
    "custom ios app development company in uae",
    "eCommerce",
    "AI language model",
    "app development company in Dubai",
    "CRM platforms",
    "Android application development",
    "eCommerce app",
    "asset management",
    "SCM software",
    "Dubai App Development Experts",
    "create a music app",
    "Python app development in UAE",
    "fine-tune LLMs",
    "agentic AI",
    "custom website development",
    "Best Web Design Company in Dubai",
    "developing a user-friendly dating app",
    "services to help businesses establish",
    "developing custom software",
    "cost of developing enterprise software",
    "Create Powerful Mobile Apps with – Leading Developers in Saudi Arabia",
    "Custom payment software solutions",
    "A Step-by-Step Guide to Ticket Booking App Development in 2026",
    "payment features",
    "React Native Mobile app development in Dubai",
    "enterprise ERP systems",
    "Python application development firm in Dubai",
    "costs to develop an app",
    "making mobile apps",
    "software development company.",
    "AI app development companies",
    "app development costs",
    "well-designed website",
    "custom software development services in Dubai",
    "Top Mobile App Development Company in Saudi Arabia",
    "develop mobile apps",
    "Transportation Management Systems",
    "web application development companies",
    "software development solutions",
    "web application development services in Duba",
    "launch your betting software development platform",
    "web app development companies in Dubai",
    "developing an mobile app",
    "custom mobile app development services in Dubai",
    "Contactless NFC payments",
    "professional web design company",
    "mobile company",
    "websites",
    "ERP software solutions",
    "Leading Andriod app development company in Dubai",
    "build a custom app",
    "web development company in Sharjah",
    "native iOS app development services",
    "application developers in Dubai",
    "companies in Saudi Arabia",
    "build your retail software",
    "Django framework services",
    "custom mobile app development company Dubai",
    "software development services in Abu Dhabi",
    "web developers",
    "develop a similar application",
    "cost to develop transport and logistic app",
    "custom iPhone app development company",
    "make a better mobile app",
    "create an app like Tinder",
    "Android App Development company in Dubai.",
    "container software can boost supply chain",
    "UAE App Developers",
    "banking industry",
    "Digital Marketing Services",
    "creating custom mobile apps",
    "Web App Development Company Dubai",
    "Python app development",
    "develop a pharmacy delivery app",
    "Web Development Company in Duba",
    "develop a custom AI solution or a chatbot",
    "web application company in Dubai",
    "mobile app development services Dubai",
    "application",
    "app developers",
    "iPhone app development",
    "mobile app development compa ny dubai",
    "project management solutions",
    "Android app developers",
    "web application development services Dubai",
    "trusted partner for businesses in Dubai",
    "mobile app development company in UAE",
    "mobile app development company in Riyadh",
    "generative AI chatbots",
    "python development company dubai",
    "develops apps",
    "0% discount on Mobile App Services in UAE",
    "healthcare industry",
    "cost of developing native apps",
    "mobile app development services in Dubai",
    "hire mobile app development company",
    "iOS app development company in Dubai.",
    "food service providers",
    "W eb App Development Company in Dubai",
    "Application Development company Dubai",
    "CRM systems",
    "custom mobile app development",
    "Web App Development company in Duba",
    "Ecommerce development companies in the UAE",
    "healthcare providers",
    "mobile app development partner",
    "website development company",
    "leading mobile app development company",
    "mobile app development company in Egypt",
    "mobile app development comapny",
    "Construction Management Software Costs: A Complete Guide",
    "Progressive Web Apps",
    "LLMs in enterprises",
    "custom app development company",
    "app development companies",
    "React Native development services",
    "Hiring Android developers",
    "Android app development",
    "managing energy",
    "mobile app development companies in Kuwait",
    "Visit my website",
    "Website Development Company in Abu Dhabi",
    "app development projects",
    "implementation of chatbots",
    "cost to develop a pharmacy app",
    "award-winning mobile app development company in Dubai",
    "Supermarkets and Grocery Stores",
    "Web App Development Comapny in Dubai",
    "Be part of an organisation",
    "banking systems",
    "developing Android apps",
    "autonomous AI agents",
    "developing a successful mobile app",
    "software development teams",
    "cost of a developer",
    "developing a mobile app in Dubai",
    "mobile app solutions",
    "supermarkets and grocery businesses",
    "iOS app development services in Dubai",
    "application development company in Dubai",
    "Warehouse Management Systems",
    "iOS developers",
    "mobile app development company dubai",
    "Integrating AI in CRM software",
    "Taxi App Development Services",
    "How Much Does It Cost To Develop Inventory Management Software?",
    "iPhone app development company in Dubai",
    "building basic web applications",
    "Generative AI models",
    "Mobile App Development Company in Dubai.",
    "eCommerce app development company in Dubai",
    "software application",
    "create successful mobile apps",
    "mobile app development company based in Cairo",
    "Top Android app Development Companies In Dubai",
    "grocery delivery platforms",
    "create a web app",
    "Custom Software Development Company in UAE",
    "app development experts in Dubai",
    "software development partner",
    "Fine-tuning",
    "B2B banking",
    "web development offers",
    "cost to develop custom software",
    "create software solutions",
    "Belong to a team",
    "Software-as-a-service provider",
    "top-rated digital marketing company",
    "app development companies in dubai",
    "Flutter App Development Services",
    "cost to add NFC cards to your existing CRM",
    "logistics",
    "Launch an app development",
    "custom Android app development services",
    "web development comapny in Dubai",
    "real estate app development",
    "development and maintenance costs",
    "AI-powered retail solutions",
    "Python application development company Dubai",
    "app development services",
    "No.1 Mobile App Development Company UAE – Trusted & Professional Services",
    "iOS app development service",
    "Das Produkt auf der Firmen Webseite finden",
    "web development companies in Abu Dhabi",
    "LLMs",
    "delivering cutting-edge mobile solutions",
    "Android app development in Abu Dhabi",
    "developing a maintenance app",
    "web developers and companies",
    "Website Development Company in Abu Dhabi.",
    "professional web application development company",
    "React Native App development Company Dubai",
    "supply chain solutions",
    "healthcare costs",
    "mobile app development companies in Dubai",
    "website design services",
    "cybercriminals",
    "Web Design Agency in Dubai",
    "cost of developing the software",
    "mobile app developer in Dubai",
    "Top Managed IT Services Companies in Dubai",
    "CRM Development Services",
    "creating an app",
    "custom mobile app development services",
    "building a chatbot",
    "web design services in Duba",
    "custom mobile app",
    "AI solutions are simplifying supply chain automation",
    "travel booking app development",
    "website development in Dubai",
    "React Native developers",
    "cross platform app development Kuwait",
    "Mobile App Development Cost in Dubai",
    "best mobile app developers",
    "Leading Web App Development Company in Dubai",
    "How To Develop Custom Payment Gateway",
    "build proactive AI agents",
    "customer relationship management (CRM)",
    "python application development",
    "digital healthcare solutions",
    "Android apps for Dubai companies",
    "mobile app developer in UAE",
    "​ CO. L.L.C",
    "Developing mobile apps for Android and iOS",
    "developers to develop apps",
    "Android and iOS app development",
    "Android app developers in Saudi Arabia",
    "telemedicine consultations",
    "best app development services in Abu Dhabi",
    "mobile app development company in the Middle Eas",
    "develop an on-demand pickup and drop application",
    "mobile and web app development",
    "software development agency",
    "Mobile app development costs in UAE",
    "e-commerce app development costs in Dubai",
    "grocery delivery apps",
    "web app development services dubai",
    "PWA development Dubai services",
    "web app development company in UAE",
    "How Dubai's Web App Innovators are Transforming the Tech Industry",
    "application development",
    "hire developers to create an Android app",
    "website design company in UAE",
    "integrating AI chatbots",
    "mobile app development in Dubai",
    "web application development company in UAE",
    "mobile companies",
    "develop a mobile app in Duba",
    "development team",
    "Web and software development company in Dubai",
    "creating mobile apps",
    "healthcare CRM development app cost",
    "Web Application Development Company Dubai.",
    "Building custom employee time tracking app",
    "Why Is an Ideal Partner For Software Development Services",
    "eCommerce app development may help your business grow",
    "IoT Application Services",
    "#1 Top-Notch Mobile App Development Company | UAE",
    "Top Level Mobile App Development In Dubai",
    "#1 On-Demand App Development Dubai | UAE",
    "Leading App development Company Dubai - UAE",
    "Machine learning",
    "Hire Android Developer",
    "elearning app development company",
    "Dubai’s Trusted App Development Company for Business-Driven Mobile Solutions",
    "taxi app development company",
    "dating app development company",
    "Mobile App Development Company in Dubai | App development Dubai",
    "app development Dubai",
    "food delivery app solution",
    "Salon App Development Company",
    "AI app development",
    "budget $15",
    "000–$25",
    "000 per year",
    "healthcare app development",
    "Uber Clone",
    "healthcare software development services",
    "Top 10 AI Development Companies in Dubai",
    "AI integration",
    "app development company Dubai",
    "AI development services",
    "healthcare app development company",
    "delivery app development",
    "iphone application development in dubai",
    "Natural Language Processing",
    "AI app development company",
    "Uber like app development",
    "taxi app development",
    "Privacy Policy",
    "Mobile Application Development",
    "shield",
    "taxi dispatch software",
    "Salon App Development Services",
    "online marketplace development",
    "AI-powered chatbots",
    "Portfolio",
    "AI fitness app development company",
    "Make uber like app",
    "hire a developer",
    "On-Demand App Development",
    "hire top developers",
    "create food delivery app",
    "AI chatbot development company",
    "healthcare software development company",
    "AI consulting services",
    "build marketplace platform",
    "AI consulting company",
    "generative AI development services",
    "AI Healthcare App Development company",
    "AI Integration Services",
    "create delivery app",
    "Machine Learning (ML)",
    "AI-powered dating app development",
    "Launch Your Own Custom Mobile App & Website",
    "How we work",
    "Why Choose us",
    "AI fitness app development",
    "create online marketplace",
    "fintech app development",
    "delivery app builder",
    "marketplace app development",
    "healthcare app development companies",
    "Build uber app",
    "Create uber like app",
    "Create A Fitness App In the USA",
    "AI application development",
    "Real estate",
    "Create taxi app",
    "Ecommerce app builder",
    "top mobile app development companies in Dubai",
    "fintech app development company in Dubai",
    "SaaS development company",
    "dating app development company in Dubai",
    "ecommerce app development",
    "AI-powered mobile applications",
    "build taxi app",
    "AI automation",
    "Enhance Your Delivery Operations with Software Delivery Management",
    "Grocery Delivery",
    "AI-powered automation",
    "financial software development company",
    "Make Marketplace Website",
    "ecommerce app development Dubai",
    "real estate app development company",
    "OTT platform development",
    "AI-powered fitness applications",
    "Best social media app development company in the USA",
    "Laundry",
    "dating app development companies",
    "AI Chatbot",
    "machine learning model development",
    "E-commerce",
    "build delivery app",
    "AI food delivery app development company in Dubai",
    "Live streaming app development",
    "AI-powered fintech app development",
    "Best Elearning App Development Company",
    "Superb Food Delivery App Development Company",
    "AI-powered solutions",
    "AI Agents for Finance: Reshaping the Financial Services in 2025",
    "AI Agent Development Company",
    "رابط الشركة",
    "top dating app development companies",
    "make delivery app",
    "AI Real Estate App Development Company",
    "Real estate tokenization",
    "online marketplace builder",
    "Food App Development",
    "best app development company",
    "Telegram Mini Apps",
    "AI-driven solutions",
    "AI app development in 2026",
    "hire ChatGPT developers",
    "ecommerce development company in Dubai",
    "food delivery app development solutions",
    "CB Food",
    "build a dating app",
    "ecommerce development Dubai",
    "mobile app development company Abu Dhabi",
    "Top Marketplace App Development Company",
    "video streaming app development company",
    "Uber clone app",
    "hire iOS developer",
    "AI dating app development",
    "AI Real Estate App Development",
    "most famous Uber clone app development company",
    "OTT platform development company",
    "Smart Contract",
    "ERP",
    "Dating & Social Media",
    "Wallet Development",
    "AI development companies in Dubai",
    "SaaS application development",
    "ICO Development",
    "CB Apps",
    "Dating App",
    "Pharmacy",
    "story",
    "Nutrition app",
    "AI development company in 2026",
    "AI integrations",
    "Rideshare",
    "Online Marketplace",
    "machine learning integration",
    "CB Rides",
    "OTT",
    "Live Demos",
    "here",
    "Video Streaming",
    "Sports Betting",
    "CB Consult",
    "AI Real Estate app development services",
    "Social Media",
    "Generative AI Development",
    "public",
    "Taxi Booking",
    "CB Orders",
    "Wallet",
    "mobile app development company in the USA",
    "real estate app development services",
    "healthcare app development in 2026",
    "Grocery Delivery App development",
    "Custom dating app development",
    "Pickup & Delivery",
    "CB Dispatcher",
    "Fantasy & Betting",
    "Android app development Dubai",
    "Asset Tokenization",
    "CB Tensor AI",
    "mobile app development company in Bahrain",
    "AI mobile app development",
    "dating app development company in the USA",
    "Social Media App Development Company",
    "grocery delivery app development company",
    "elearning app development services",
    "View Case Study",
    "cost of AI development",
    "Fantasy app",
    "Yoga & Medition",
    "Logistics & Delivery",
    "healthcare software development",
    "AI pharmacy delivery app development company in Dubai",
    "Home Services",
    "Insurance App",
    "Adaptive AI Development",
    "food delivery software",
    "dating app development services",
    "AI grocery app development company in Dubai",
    "AI custom social media app development company in Dubai",
    "E-learning",
    "About Us",
    "AI app development company in the USA",
    "AI Virtual Companion",
    "How to Create Your Own App in 2024",
    "AI healthcare app development companies",
    "SaaS product development company",
    "Lorem ipsum dolor sit amet",
    "consectetur adipiscing elit.",
    "Return Policy",
    "mobile app development company in the UAE",
    "Cross Platform App Development",
    "Ideation & Design",
    "E-commerce App",
    "Food Delivery",
    "AI online consultation app development company in Dubai",
    "best mobile app development company",
    "best delivery management software",
    "Build an App",
    "Terms & conditions",
    "On Demand Delivery",
    "leading AI taxi app development company in Dubai",
    "best generative AI development services",
    "AI dating app development company",
    "on-demand delivery app",
    "app development company in UAE",
    "Travel & Transport",
    "white label app solution",
    "AI agent development",
    "uber like app",
    "casino app development services",
    "Dating app developers",
    "Service",
    "Hire app developer",
    "app development company Abu Dhabi",
    "AI solutions",
    "Healthcare",
    "Contact Us",
    "Generative AI applications",
    "AI healthcare software development services in Dubai",
    "creating a fitness app",
    "top-rated mobile app development companies in the USA",
    "create a real estate app",
    "AI-powered applications",
    "creating a taxi app",
    "On-Demand",
    "Real Estate Tokenization Services | Real Estate Tokenization Company",
    "growth",
    "GenAI application development services",
    "AI automation agency",
    "Taxi & Transportation",
    "Build a real estate app",
    "About",
    "machine learning algorithms",
    "create an app",
    "AI application development services",
    "AI-powered mobile app development",
    "AI-powered healthcare applications",
    "On-demand model",
    "app development company in the UAE",
    "Privacy",
    "AI healthcare app development",
    "dating app development company in USA",
    "best AI development company",
    "intelligent chatbots",
    "Uber-like app development",
    "natural language processing (NLP)",
    "how to create an app",
    "AI-powered healthcare app development",
    "uber clone apps",
    "create grocery app",
    "Gojek clone app",
    "cost of AI app development in Dubai",
    "AI-driven dating app development",
    "Grocery App Development",
    "top AI development company",
    "AI Voice Assistant Development Guide",
    "AI FinTech development company",
    "healthcare app development services",
    "on-demand app development services",
    "app development in Dubai",
    "SaaS Business Model for Tech Startups in 2023: A Beginner's Guide ...",
    "How To Create On-Demand Home Services Booking Apps Like Handyman",
    "Thumbtack",
    "and TaskRabbit?",
    "best fitness app development",
    "Refund Policy",
    "The Role of AI and ML in Custom Software Development",
    "custom fintech app development company",
    "TikTok clone",
    "hire mobile app developer",
    "verified_user",
    "AI application development company",
    "delivery management software",
    "Visit",
    "AI grocery delivery app development company",
    "AI healthcare app developers",
    "app development UAE",
    "Doordash",
    "real estate apps",
    "AI-driven healthcare apps",
    "Lab",
    "mobile app development firm",
    "AI-powered fintech solutions",
    "AI chatbot development services",
    "leading AI Uber-like app development company in Dubai",
    "Saas app development company",
    "top 10 mobile app development companies in Dubai",
    "AI healthcare software development",
    "Artificial Intelligence in Mobile Application",
    "AI healthcare app",
    "project manager",
    "AI development company in the USA",
    "AI development service",
    "healthcare development companies of 2026",
    "trusted dating app development companies worldwide",
    "machine learning models",
    "OTT app development company",
    "Terms of use",
    "Zomato",
    "premium mobile app development company in UAE",
    "real estate mobile app development",
    "generative AI development company",
    "AI taxi app development company",
    "grocery app development services",
    "top app development companies in Dubai",
    "top dating app development company",
    "make an ecommerce app",
    "AI development companies in the UAE",
    "mobile app development companies in Abu Dhabi",
    "AI-powered apps",
    "AI logistics app development company in Dubai",
    "fintech app development services",
    "SaaS development services",
    "on-demand fitness app developmen",
    "custom food delivery application development",
    "AI-powered app development",
    "AI app developers",
    "food delivery app development company",
    "fitness app development services",
    "create a laundry app",
    "gaming app development company",
    "Real Estate Mobile App Development Company",
    "AI-driven app development",
    "leading fintech app development company",
    "AI machine learning",
    "marketplace development",
    "Terms",
    "Gojek clone",
    "Henry Pol",
    "building a successful dating app",
    "top-rated mobile app development company",
    "best artificial intelligence development companies",
    "AI-Powered Chatbot development Company",
    "Watch Now",
    "app development compan",
    "building a dating app",
    "Top 10 Dating App Development Companies in 2026",
    "NFT Development",
    "top dating app development companies in California",
    "AI healthcare software development services",
    "app development agency",
    "leading AI-based mobile app development Company in Dubai",
    "AI Development Company in USA",
    "fitness app",
    "top fintech software development company",
    "10 trusted AI development companies",
    "Marketplace and platform solutions",
    "healthcare app development in the UAE",
    "AI development companies shaping the future of Dubai",
    "Premium App Development",
    "intelligent mobile",
    "Uber-like app development company in Dubai",
    "leading AI Grocery Delivery development company",
    "restaurant app development services",
    "AI beauty app development company in Dubai",
    "Top healthcare app development companies",
    "AI integration development",
    "AI-powered automation solutions",
    "reliable AI development company",
    "AI real estate app development company in Dubai",
    "healthcare software development company services",
    "8 reliable dating app development companies in Dubai",
    "Fintech and banking",
    "A Comprehensive Guide to Custom Software Development for 2025",
    "AI-powered fitness app development company",
    "AI Uber-like app development company in UAE",
    "On-demand app development service",
    "Healthcare apps",
    "eLearning software development",
    "healthcare app development services in the USA",
    "Real Estate Platform",
    "real estate app solutions",
    "AI models",
    "Hire our team",
    "AI-powered mobile apps",
    "AI integration development agency",
    "Top ChatGPT Development Company",
    "Custom AI development",
    "OTT app development",
    "AI integration Development company",
    "Grocery App Development Company",
    "AI Beauty Salon App Development",
    "top-tier healthcare app development company",
    "Launch Your Own Fitness App",
    "AI integration service",
    "Dating App Development Companies in Dubai",
    "Peer-to-peer (P2P) marketplace",
    "create real estate app",
    "Dietary",
    "10 best healthcare app development services in the UAE for 2026",
    "AI logistics app development companies in Dubai",
    "top AI healthcare app development companies",
    "AI fitness app developers in Dubai",
    "top education app development company",
    "best SaaS development company",
    "develop astrology app",
  ],
  authors: [{ name: "Technioz Team", url: "https://technioz.com" }],
  creator: "Technioz",
  publisher: "Technioz",
  robots: {
    index: true,
    follow: true,
    googleBot: "index, follow, max-video-preview:-1, max-image-preview:large, max-snippet:-1",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://technioz.com",
    siteName: "Technioz",
    title: "Technioz - Innovative Software Development & IT Solutions",
    description:
      "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project and get a custom roadmap.",
    images: [
      {
        url: "/logo.webp",
        width: 1200,
        height: 630,
        alt: "Technioz - Software Development Company",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Technioz - Innovative Software Development & IT Solutions",
    description:
      "Leading software development company providing custom web applications, mobile apps, AI solutions, and IT consulting services. Book a free 30-minute consultation call to discuss your project.",
    images: ["/logo.webp"],
  },
  alternates: {
    canonical: "https://technioz.com",
  },
  verification: {
    other: {
      "msvalidate.01": "815380119EFE87A1BC1C3A90FA4B6EB6",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <head>
        <JsonLd />
      </head>
      <body>
        <Nav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
